### ISSUE TITLE
Certain familiar's stats are not showing the correct pope

### ISSUE THREAD

**Issue by yuhhaur** [chinhodado/BBDB#7]
Some of the latest familiars' pope stats are not shown correctly.

Botis are wrong
https://lh4.googleusercontent.com/-svucGM8DXRo/VLUGFh4UNWI/AAAAAAAAEuM/GWIct4Fl-oI/w431-h766-no/Screenshot_2015-01-13-19-46-55.png

Lache is incorrect
https://lh3.googleusercontent.com/-7TX0RahZ3E8/VLUGG3DOgPI/AAAAAAAAEuQ/fIJ9qzaQLhI/w431-h766-no/Screenshot_2015-01-13-19-47-06.png

Deimos is correct:
https://lh4.googleusercontent.com/-SqJtlFrPlKU/VLUGHyBfoJI/AAAAAAAAEuY/yMqXV0RzXv8/w431-h766-no/Screenshot_2015-01-13-19-47-16.png

Previous day Tyche and the rest is correct too:
https://lh5.googleusercontent.com/-6CfdAfyCc-c/VLUGEP4ngcI/AAAAAAAAEuA/bpL6Hha2ato/w431-h766-no/Screenshot_2015-01-13-19-47-26.png

I thought it is supposed to be auto generated?

**Comment by chinhodado** [comment]
Hm yes it is supposed to be auto generated. I'll take a look later today. In the mean time, maybe you can try clearing the cache and/or reinstall it to see if it fixes it?

**Comment by chinhodado** [comment]
It is indeed a bug. I have updated to v1.5.7 which should fix it.

**Comment by yuhhaur** [comment]
bravo with the swift update.
